Tannholt_Cave3_MapScripts::
	.byte 0


Tannholt_Cave3_Mason::
# 4 "data/maps/Tannholt_Cave3/scripts.pory"
	lockall
# 5 "data/maps/Tannholt_Cave3/scripts.pory"
	faceplayer
# 6 "data/maps/Tannholt_Cave3/scripts.pory"
	msgbox Tannholt_Cave3_Mason_Text_0
# 7 "data/maps/Tannholt_Cave3/scripts.pory"
	releaseall
	return


Tannholt_Cave3_Mason_Text_0:
# 6 "data/maps/Tannholt_Cave3/scripts.pory"
	.string "I collect stones! And then I hit stones\n"
	.string "with other stones. When they are flat, I\l"
	.string "put them on the ground. Nice to walk on,\l"
	.string "feet don't get muddy.$"
