Spragholt_Cave3_MapScripts::
	.byte 0


TestScript::
# 4 "data/maps/Spragholt_Cave3/scripts.pory"
	applymovement 1, TestScript_Movement_0
# 5 "data/maps/Spragholt_Cave3/scripts.pory"
	applymovement 2, TestScript_Movement_0
	return


# 4 "data/maps/Spragholt_Cave3/scripts.pory"
TestScript_Movement_0:
# 4 "data/maps/Spragholt_Cave3/scripts.pory"
	exit_pokeball
# 4 "data/maps/Spragholt_Cave3/scripts.pory"
	delay_16
# 4 "data/maps/Spragholt_Cave3/scripts.pory"
	delay_16
# 4 "data/maps/Spragholt_Cave3/scripts.pory"
	delay_16
# 4 "data/maps/Spragholt_Cave3/scripts.pory"
	delay_16
# 4 "data/maps/Spragholt_Cave3/scripts.pory"
	delay_16
# 4 "data/maps/Spragholt_Cave3/scripts.pory"
	delay_16
# 4 "data/maps/Spragholt_Cave3/scripts.pory"
	delay_16
# 4 "data/maps/Spragholt_Cave3/scripts.pory"
	delay_16
# 4 "data/maps/Spragholt_Cave3/scripts.pory"
	enter_pokeball
# 4 "data/maps/Spragholt_Cave3/scripts.pory"
	delay_16
# 4 "data/maps/Spragholt_Cave3/scripts.pory"
	delay_16
# 4 "data/maps/Spragholt_Cave3/scripts.pory"
	delay_16
# 4 "data/maps/Spragholt_Cave3/scripts.pory"
	delay_16
# 4 "data/maps/Spragholt_Cave3/scripts.pory"
	delay_16
# 4 "data/maps/Spragholt_Cave3/scripts.pory"
	delay_16
# 4 "data/maps/Spragholt_Cave3/scripts.pory"
	delay_16
# 4 "data/maps/Spragholt_Cave3/scripts.pory"
	delay_16
	step_end
